name: EvaliaTools
version: '${project.version}'
main: com.bgsoftware.wildtools.WildToolsPlugin
api-version: '1.20'
author: Kazotaruu
description: Custom Minecraft tools plugin based on WildTools
website: https://github.com/kazotaruumc72/EvaliaTool

softdepend:
  - Vault
  - WorldGuard
  - GriefPrevention
  - Factions
  - FactionsUUID
  - MassiveCoreFactions
  - SavageFactions
  - WildStacker
  - RoseStacker
  - UltimateStacker